src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MovieRepository::class)]
class Movie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_publish = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $duree = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'movie')]
    private ?Director $director = null;

    #[ORM\ManyToMany(targetEntity: Genre::class, inversedBy: 'movie')]
    private Collection $genres;

    #[ORM\ManyToMany(targetEntity: Actor::class, inversedBy: 'movies')]
    private Collection $actors;

    public function __construct()
    {
        $this->genres = new ArrayCollection();
        $this->actors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDatePublish(): ?\DateTimeInterface
    {
        return $this->date_publish;
    }

    public function setDatePublish(?\DateTimeInterface $date_publish): self
    {
        $this->date_publish = $date_publish;

        return $this;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(?\DateTimeInterface $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDirector(): ?Director
    {
        return $this->director;
    }

    public function setDirector(?Director $director): self
    {
        $this->director = $director;

        return $this;
    }

    /**
     * @return Collection<int, Genre>
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres->add($genre);
            $genre->addMovie($this);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        if ($this->genres->removeElement($genre)) {
            $genre->removeMovie($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Actor>
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(Actor $actor): self
    {
        if (!$this->actors->contains($actor)) {
            $this->actors->add($actor);
            $actor->addMovie($this);
        }

        return $this;
    }

    public function removeActor(Actor $actor): self
    {
        if ($this->actors->removeElement($actor)) {
            $actor->removeMovie($this);
        }

        return $this;
    }
}

src/Form/MovieType.php
<?php

namespace App\Form;

use App\Entity\Genre;
use App\Entity\Movie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class MovieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('date_publish', null, [
                'format'=>'ddMMMMyyyy',
                'years' => range(1930, 2026)
            ])
            ->add('duree')
            ->add('image')
            ->add('director')
            ->add('genres')
            ->add('actors')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Movie::class,
        ]);
    }
}

src/Controller/MovieController.php
<?php

namespace App\Controller;

use App\Entity\Movie;
use App\Form\MovieType;
use App\Repository\MovieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/movie')]
class MovieController extends AbstractController
{
    #[Route('/', name: 'app_movie_index', methods: ['GET'])]
    public function index(MovieRepository $movieRepository): Response
    {
        return $this->render('movie/index.html.twig', [
            'movies' => $movieRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_movie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MovieRepository $movieRepository): Response
    {
        $movie = new Movie();
        $form = $this->createForm(MovieType::class, $movie);
       
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                //code...
                $movieRepository->save($movie, true);
                return $this->redirectToRoute('app_movie_index', [], Response::HTTP_SEE_OTHER);
            } catch (\Exception $e) {
                $this->addFlash("error", "Formulaire invalide");

            }

        }

        return $this->render('movie/new.html.twig', [
            'movie' => $movie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_movie_show', methods: ['GET'])]
    public function show(Movie $movie=null): Response
    {
        if ($movie == null) {
            return $this->flashMessage("error", "Film inexistant");
        }
        return $this->render('movie/show.html.twig', [
            'movie' => $movie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_movie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Movie $movie = null, MovieRepository $movieRepository): Response
    {
        if ($movie == null) {
            return $this->flashMessage("error", "Film inexistant");
        }
        $form = $this->createForm(MovieType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            try {
                $movieRepository->save($movie, true);
                return $this->redirectToRoute('app_movie_index', [], Response::HTTP_SEE_OTHER);
            } catch (\Exception $e) {
                $this->addFlash("error", "modification invalide");

            }
            
        }

        return $this->renderForm('movie/edit.html.twig', [
            'movie' => $movie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_movie_delete', methods: ['POST'])]
    public function delete(Request $request, Movie $movie=null, MovieRepository $movieRepository): Response
    {
        if ($movie == null) {
            return $this->flashMessage("error", "Film inexistant");
        }
        if ($this->isCsrfTokenValid('delete'.$movie->getId(), $request->request->get('_token'))) {
            $movieRepository->remove($movie, true);
        }

        return $this->redirectToRoute('app_movie_index', [], Response::HTTP_SEE_OTHER);
    }


    private function flashMessage($paramType, $paramMessage) {
        $this->addFlash($paramType, $paramMessage);
            return $this->redirectToRoute('app_movie_index');

    }
}

templates/movie/_delete_form.html.twig
<form method="post" action="{{ path('app_movie_delete', {'id': movie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ movie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/movie/_form.html.twig
<div class="container">
{{ form_start(form) }}
    {# {{ form_widget(form) }} #}
    <div class="mb-3">
    {{ form_row(form.title) }}
    </div>
    <div class="mb-3">
    {{ form_row(form.description) }}
    </div>
    {{ form_rest(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
</div>

templates/movie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Movie{% endblock %}

{% block body %}
    <h1>Edit Movie</h1>

    {{ include('movie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_movie_index') }}">back to list</a>

    {{ include('movie/_delete_form.html.twig') }}
{% endblock %}

templates/movie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movie index
{% endblock %}

{% block body %}
		<h1>Movie index</h1>
		<div>
			{% for movie in movies %}
				<div class="card" style="width: 18rem;">
					<img src="{{movie.image}}" class="card-img-top" alt="...">
					<div class="card-body">
						<h5 class="card-title">{{movie.title}}</h5>
						<div class="row">
							<a href="{{ path('app_movie_edit', {'id': movie.id}) }}" class="btn btn-primary col mx-1"><i class="bi bi-pencil-square"></i> Editer</a>
							<a href="{{ path('app_movie_show', {'id': movie.id}) }}" class="btn btn-info col mx-1"><i class="bi bi-card-heading"></i> Détail</a>

						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	<a href="{{ path('app_movie_new') }}">Create new</a>
	


{% endblock %}

templates/movie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Movie
{% endblock %}

{% block body %}
		<h1>Create new Movie</h1>

		{{ include('movie/_form.html.twig') }}

		<a href="{{ path('app_movie_index') }}">back to list</a>
	
{% endblock %}

templates/movie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movie{% endblock %}

{% block body %}
    <h1>Movie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ movie.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ movie.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ movie.description }}</td>
            </tr>
            <tr>
                <th>Date_publish</th>
                <td>{{ movie.datePublish ? movie.datePublish|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Duree</th>
                <td>{{ movie.duree ? movie.duree|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ movie.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_movie_index') }}">back to list</a>

    <a href="{{ path('app_movie_edit', {'id': movie.id}) }}">edit</a>

    {{ include('movie/_delete_form.html.twig') }}
{% endblock %}